In [1]:
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats as stats
from scipy.stats import ttest_ind
from random import randint

In [2]:
#import cleaned data as csv file.  Need to encode with ANSI due to special characters
csv_path_clean = "../data/Cleaned_Data.csv"
solar_clean_df = pd.read_csv(csv_path_clean, delimiter=",", encoding="ISO-8859-1")

#show head of dataframe to ensure proper loading
solar_clean_df.head()

,Unnamed: 0,tile_count,solar_system_count,total_panel_area,fips,average_household_income,county,education_bachelor,education_college,education_doctoral,...,incentive_residential_state_level,incentive_nonresidential_state_level,net_metering,feedin_tariff,cooperate_tax,property_tax,sales_tax,rebate,avg_electricity_retail_rate,Solar_Status
0,0,0,0,0.000000,27145011200,70352.78987,Stearns County,569,1690,13,...,11,13,34,0,0,25,12,0,9.46,No
1,2,3,3,64.505776,27145011302,71496.88658,Stearns County,854,1459,31,...,11,13,34,0,0,25,12,0,9.46,Yes
2,3,0,0,0.000000,27145011304,86840.15275,Stearns County,640,1116,68,...,11,13,34,0,0,25,12,0,9.46,No
3,4,5,5,164.583303,27145011400,89135.31560,Stearns County,654,1314,15,...,11,13,34,0,0,25,12,0,9.46,Yes
4,5,0,0,0.000000,27145011500,62225.90361,Stearns County,522,1395,24,...,11,13,34,0,0,25,12,0,9.46,No

In [3]:
reduced_solar_df = solar_clean_df.loc[:, ["state", "electricity_price_residential", "electricity_price_commercial","electricity_price_industrial", "incentive_count_residential","incentive_count_nonresidential"]]
reduced_solar_df

,state,electricity_price_residential,electricity_price_commercial,electricity_price_industrial,incentive_count_residential,incentive_count_nonresidential
0,mn,12.12,9.44,7.02,34,39
1,mn,12.12,9.44,7.02,34,39
2,mn,12.12,9.44,7.02,34,39
3,mn,12.12,9.44,7.02,34,39
4,mn,12.12,9.44,7.02,34,39
5,mn,12.12,9.44,7.02,34,39
6,mn,12.12,9.44,7.02,34,39
7,mn,12.12,9.44,7.02,34,39
8,mn,12.12,9.44,7.02,34,39
9,mn,12.12,9.44,7.02,34,39
10,mn,12.12,9.44,7.02,34,39
11,mn,12.12,9.44,7.02,34,39
12,mn,12.12,9.44,7.02,34,39
13,mn,12.12,9.44,7.02,34,39
14,mn,12.12,9.44,7.02,34,39
15,mn,12.12,9.44,7.02,34,39
16,mn,12.12,9.44,7.02,34,39
17,mn,12.12,9.44,7.02,34,39
18,mn,12.12,9.44,7.02,34,39
19,ny,18.54,15.31,6.31,28,36
20,ny,18.54,15.31,6.31,28,36
21,ny,18.54,15.31,6.31,28,36
22,ny,18.54,15.31,6.31,28,36
23,ny,18.54,15.31,6.31,28,36
24,ny,18.54,15.31,6.31,28,36
25,ny,18.54,15.31,6.31,28,36
26,ny,18.54,15.31,6.31,28,36
27,ny,18.54,15.31,6.31,28,36
28,ny,18.54,15.31,6.31,28,36
29,ny,18.54,15.31,6.31,28,36
...,...,...,...,...,...,...
63817,in,11.57,9.78,6.86,13,22
63818,tn,10.30,10.16,6.17,10,19
63819,tn,10.30,10.16,6.17,10,19
63820,tn,10.30,10.16,6.17,10,19
63821,tn,10.30,10.16,6.17,10,19
63822,tn,10.30,10.16,6.17,10,19
63823,ut,10.88,8.62,6.17,19,26
63824,ut,10.88,8.62,6.17,19,26
63825,tx,11.56,8.15,5.59,47,54
63826,tx,11.56,8.15,5.59,47,54
63827,tx,11.56,8.15,5.59,47,54
63828,tx,11.56,8.15,5.59,47,54
63829,tx,11.56,8.15,5.59,47,54
63830,tx,11.56,8.15,5.59,47,54
63831,tx,11.56,8.15,5.59,47,54
63832,tx,11.56,8.15,5.59,47,54
63833,tx,11.56,8.15,5.59,47,54
63834,nd,9.62,8.83,8.07,10,17
63835,ia,11.63,8.92,5.90,18,26
63836,ia,11.63,8.92,5.90,18,26
63837,ia,11.63,8.92,5.90,18,26
63838,ia,11.63,8.92,5.90,18,26
63839,ga,11.54,9.89,5.87,19,22
63840,co,12.12,9.88,7.40,43,50
63841,co,12.12,9.88,7.40,43,50
63842,co,12.12,9.88,7.40,43,50
63843,ok,10.14,7.68,5.35,8,19
63844,ok,10.14,7.68,5.35,8,19
63845,ok,10.14,7.68,5.35,8,19
63846,tx,11.56,8.15,5.59,47,54

In [4]:
grouped_solar_df = reduced_solar_df.groupby(['state'])

grouped_solar_df.head()

,state,electricity_price_residential,electricity_price_commercial,electricity_price_industrial,incentive_count_residential,incentive_count_nonresidential
0,mn,12.12,9.44,7.02,34,39
1,mn,12.12,9.44,7.02,34,39
2,mn,12.12,9.44,7.02,34,39
3,mn,12.12,9.44,7.02,34,39
4,mn,12.12,9.44,7.02,34,39
19,ny,18.54,15.31,6.31,28,36
20,ny,18.54,15.31,6.31,28,36
21,ny,18.54,15.31,6.31,28,36
22,ny,18.54,15.31,6.31,28,36
23,ny,18.54,15.31,6.31,28,36
95,ca,16.99,15.73,12.17,75,85
96,ca,16.99,15.73,12.17,75,85
97,ca,16.99,15.73,12.17,75,85
98,ca,16.99,15.73,12.17,75,85
99,ca,16.99,15.73,12.17,75,85
2299,wa,9.09,8.22,4.35,23,30
2300,wa,9.09,8.22,4.35,23,30
2301,wa,9.09,8.22,4.35,23,30
2302,wa,9.09,8.22,4.35,23,30
2303,wa,9.09,8.22,4.35,23,30
2311,fl,11.58,9.50,8.22,41,31
2312,fl,11.58,9.50,8.22,41,31
2313,fl,11.58,9.50,8.22,41,31
2314,fl,11.58,9.50,8.22,41,31
2315,fl,11.58,9.50,8.22,41,31
2482,in,11.57,9.78,6.86,13,22
2483,in,11.57,9.78,6.86,13,22
2484,in,11.57,9.78,6.86,13,22
2485,in,11.57,9.78,6.86,13,22
2486,in,11.57,9.78,6.86,13,22
...,...,...,...,...,...,...
23083,ne,10.60,8.67,7.59,14,21
23084,ne,10.60,8.67,7.59,14,21
24153,wy,10.97,9.12,6.76,10,14
24154,wy,10.97,9.12,6.76,10,14
24155,wy,10.97,9.12,6.76,10,14
24156,wy,10.97,9.12,6.76,10,14
24157,wy,10.97,9.12,6.76,10,14
24454,ne,10.60,8.67,7.59,14,21
24455,ne,10.60,8.67,7.59,14,21
24456,ne,10.60,8.67,7.59,14,21
24821,me,15.61,12.47,9.05,15,20
24822,me,15.61,12.47,9.05,15,20
24823,me,15.61,12.47,9.05,15,20
24824,me,15.61,12.47,9.05,15,20
24825,me,15.61,12.47,9.05,15,20
29766,ut,10.88,8.62,6.17,19,26
29767,ut,10.88,8.62,6.17,19,26
29768,ut,10.88,8.62,6.17,19,26
29769,ut,10.88,8.62,6.17,19,26
29770,ut,10.88,8.62,6.17,19,26
30841,nv,12.76,9.25,6.75,18,27
30842,nv,12.76,9.25,6.75,18,27
30843,nv,12.76,9.25,6.75,18,27
30844,nv,12.76,9.25,6.75,18,27
30845,nv,12.76,9.25,6.75,18,27
36737,ri,19.29,15.78,13.76,21,26
36738,ri,19.29,15.78,13.76,21,26
36739,ri,19.29,15.78,13.76,21,26
36740,ri,19.29,15.78,13.76,21,26
36741,ri,19.29,15.78,13.76,21,26